fullnameOverride: anycommerce

## load-balancer-controller
aws-load-balancer-controller:
  clusterName: anycommerce

## Applications
carts:
  image:
    repository: 269550163595.dkr.ecr.ap-northeast-2.amazonaws.com/anycommerce/carts

order:
  image:
    repository: 269550163595.dkr.ecr.ap-northeast-2.amazonaws.com/anycommerce/order

product:
  image:
    repository: 269550163595.dkr.ecr.ap-northeast-2.amazonaws.com/anycommerce/product

recommendation:
  image:
    repository: 269550163595.dkr.ecr.ap-northeast-2.amazonaws.com/anycommerce/recommendation

user:
  image:
    repository: 269550163595.dkr.ecr.ap-northeast-2.amazonaws.com/anycommerce/user

## Ingress
##
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/actions.product: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"product","servicePort":8001,"weight":100}]}}
    alb.ingress.kubernetes.io/conditions.product: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "X-Custom-Header", "values":["awesome-sanghwa-demo-123"]}}]

    alb.ingress.kubernetes.io/actions.user: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"user","servicePort":"8002","weight":100}]}}
    alb.ingress.kubernetes.io/conditions.user: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "X-Custom-Header", "values":["awesome-sanghwa-demo-123"]}}]
      
    alb.ingress.kubernetes.io/actions.carts: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"carts","servicePort":"8003","weight":100}]}}
    alb.ingress.kubernetes.io/conditions.carts: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "X-Custom-Header", "values":["awesome-sanghwa-demo-123"]}}]

    alb.ingress.kubernetes.io/actions.order: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"order","servicePort":"8004","weight":100}]}}
    alb.ingress.kubernetes.io/conditions.order: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "X-Custom-Header", "values":["awesome-sanghwa-demo-123"]}}]

    alb.ingress.kubernetes.io/actions.recommendation: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"recommendation","servicePort":"8005","weight":100}]}}
    alb.ingress.kubernetes.io/conditions.recommendation: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "X-Custom-Header", "values":["awesome-sanghwa-demo-123"]}}]

    alb.ingress.kubernetes.io/actions.ssl-redirect: >-
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port":"443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/certificate-arn: >-
      arn:aws:acm:us-east-1:427083009791:certificate/82700287-d8bd-41c3-a9f1-1ef1909cb056
    alb.ingress.kubernetes.io/inbound-cidrs: "0.0.0.0/0"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/success-codes: 200,204,304
    kubernetes.io/ingress.class: alb
  hosts:
    - host: app.hyogrin.people.aws.dev
      paths:
        - path: /products
          backend:
            serviceName: product
            servicePort: use-annotation
        - path: /categories
          backend:
            serviceName: product
            servicePort: use-annotation

        - path: /users
          backend:
            serviceName: user
            servicePort: use-annotation
        - path: /login
          backend:
            serviceName: user
            servicePort: use-annotation

        - path: /carts
          backend:
            serviceName: carts
            servicePort: use-annotation
        - path: /sign
          backend:
            serviceName: carts
            servicePort: use-annotation

        - path: /orders
          backend:
            serviceName: order
            servicePort: use-annotation

        - path: /
          backend:
            serviceName: recommendation
            servicePort: use-annotation

        - path: /
          backend:
            serviceName: ssl-redirect
            servicePort: use-annotation
  tls:
    - hosts:
        - app.hyogrin.people.aws.dev
